/* Generated by tools/gen_5px_font.py. Do not edit.
 * Source: third_party/maurycyz_mcufont/mcufont.h (by maurycyz,
 * https://maurycyz.com/projects/mcufont/ — derived from lcamtuf's
 * font-inline.h).
 *
 * Monospace 5x5 pixel font, rendered on a 6x6 grid (advance = 6 px).
 * Coverage: space, A-Z, a-z, 0-9, and - + . , ? ! : = '
 */

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "../../lib/lvgl/lvgl.h"
#endif

/* --- Glyph bitmap (1bpp, packed bit-stream per glyph, MSB-first) --- */
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x21, 0x08, 0x02, 0x00, 0x21, 0x00, 0x00, 0x00, 0x01, 0x1C, 0x40, 0x00,
    0x00, 0x00, 0x44, 0x00, 0x00, 0x1C, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00,
    0x74, 0x6B, 0x17, 0x00, 0x65, 0x08, 0x4F, 0x80, 0x74, 0x4C, 0x8F, 0x80,
    0xF8, 0x5C, 0x1F, 0x00, 0x94, 0xBE, 0x21, 0x00, 0xFC, 0x1C, 0x1F, 0x00,
    0x74, 0x3D, 0x17, 0x00, 0xF8, 0x88, 0x84, 0x00, 0x74, 0x5D, 0x17, 0x00,
    0xFC, 0x7E, 0x10, 0x80, 0x02, 0x00, 0x80, 0x00, 0x03, 0x80, 0xE0, 0x00,
    0x74, 0x4C, 0x02, 0x00, 0x74, 0x7F, 0x18, 0x80, 0xF4, 0x7D, 0x1F, 0x00,
    0x7C, 0x21, 0x07, 0x80, 0xF4, 0x63, 0x1F, 0x00, 0xFC, 0x39, 0x0F, 0x80,
    0xFC, 0x39, 0x08, 0x00, 0x7C, 0x27, 0x17, 0x80, 0x8C, 0x7F, 0x18, 0x80,
    0xF9, 0x08, 0x4F, 0x80, 0xF8, 0x85, 0x26, 0x00, 0x95, 0x31, 0x49, 0x00,
    0x84, 0x21, 0x0F, 0x80, 0xFD, 0x6B, 0x18, 0x80, 0x8E, 0x6B, 0x38, 0x80,
    0x74, 0x63, 0x17, 0x00, 0xF4, 0x7D, 0x08, 0x00, 0x74, 0x63, 0x26, 0x80,
    0xF4, 0x7D, 0x28, 0x80, 0x7C, 0x1C, 0x1F, 0x00, 0xF9, 0x08, 0x42, 0x00,
    0x8C, 0x63, 0x17, 0x00, 0x8C, 0x54, 0xA2, 0x00, 0x8C, 0x6B, 0x5D, 0x80,
    0x8A, 0x88, 0xA8, 0x80, 0x8A, 0x88, 0x42, 0x00, 0xF8, 0x88, 0x8F, 0x80,
    0x03, 0xE3, 0x17, 0x80, 0x87, 0xA3, 0x1F, 0x00, 0x03, 0xE1, 0x07, 0x80,
    0x0B, 0xE3, 0x17, 0x80, 0x03, 0xBF, 0x07, 0x80, 0x03, 0xE1, 0xE8, 0x00,
    0x03, 0xBE, 0x1F, 0x00, 0x84, 0x3D, 0x18, 0x80, 0x20, 0x18, 0x47, 0x00,
    0x10, 0x05, 0x26, 0x00, 0x84, 0x2D, 0x8B, 0x00, 0x04, 0x21, 0x07, 0x80,
    0x07, 0xAB, 0x58, 0x80, 0x07, 0xA3, 0x18, 0x80, 0x03, 0xA3, 0x17, 0x00,
    0x07, 0xA3, 0xE8, 0x00, 0x03, 0xE2, 0xF0, 0x80, 0x03, 0xA1, 0x08, 0x00,
    0x03, 0xB0, 0x6E, 0x00, 0x07, 0xC8, 0x42, 0x00, 0x04, 0x63, 0x17, 0x00,
    0x04, 0x62, 0xA2, 0x00, 0x04, 0x6B, 0x57, 0x00, 0x04, 0x98, 0xC9, 0x00,
    0x04, 0x9C, 0x26, 0x00, 0x07, 0x88, 0x8F, 0x00,
};

/* --- Glyph descriptors (index 0 is reserved 'not found') --- */
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    { .bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 0, .adv_w = 96, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 0, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 4, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 8, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 12, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 16, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 20, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 24, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 28, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 32, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 36, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 40, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 44, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 48, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 52, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 56, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 60, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 64, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 68, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 72, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 76, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 80, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 84, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 88, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 92, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 96, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 100, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 104, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 108, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 112, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 116, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 120, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 124, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 128, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 132, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 136, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 140, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 144, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 148, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 152, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 156, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 160, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 164, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 168, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 172, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 176, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 180, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 184, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 188, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 192, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 196, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 200, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 204, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 208, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 212, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 216, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 220, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 224, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 228, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 232, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 236, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 240, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 244, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 248, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 252, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 256, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 260, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 264, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 268, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 272, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 276, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 280, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0 },
};

/* --- Unicode list (offsets from range_start) for sparse cmap --- */
static const uint16_t unicode_list_0[] = {
    0x0000, 0x0001, 0x0007, 0x000B, 0x000C, 0x000D, 0x000E, 0x0010, 0x0011, 0x0012,
    0x0013, 0x0014, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019, 0x001A, 0x001D, 0x001F,
    0x0021, 0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027, 0x0028, 0x0029, 0x002A,
    0x002B, 0x002C, 0x002D, 0x002E, 0x002F, 0x0030, 0x0031, 0x0032, 0x0033, 0x0034,
    0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003A, 0x0041, 0x0042, 0x0043, 0x0044,
    0x0045, 0x0046, 0x0047, 0x0048, 0x0049, 0x004A, 0x004B, 0x004C, 0x004D, 0x004E,
    0x004F, 0x0050, 0x0051, 0x0052, 0x0053, 0x0054, 0x0055, 0x0056, 0x0057, 0x0058,
    0x0059, 0x005A
};

/* --- Character maps: single sparse range --- */
static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x0020, .range_length = 91, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = 72,
        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

/* --- Font descriptor --- */
static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,  /* LV_FONT_FMT_TXT_PLAIN */
};

/* --- Public font --- */
const lv_font_t lv_font_cube_5px = {
    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 6,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = 0,
    .underline_thickness = 0,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};
