/* Generated by tools/gen_font.py from 6px_font.h. Do not edit. */
/* Source font: matrixserver 4x6 bitmap. Coverage: space, A-Z, 0-9, ! ? % + - . , : _ */

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "../../lib/lvgl/lvgl.h"
#endif

/* --- Glyph bitmap (1bpp, packed, MSB-first) --- */
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x44, 0x40, 0x40, 0x8A, 0x4A, 0x20, 0x04, 0xE4, 0x00, 0x00, 0x04, 0x80,
    0x00, 0xE0, 0x00, 0x00, 0x00, 0x40, 0xEA, 0xAA, 0xE0, 0x44, 0x44, 0x40,
    0xE2, 0xE8, 0xE0, 0xE2, 0x62, 0xE0, 0xAA, 0xE2, 0x20, 0xE8, 0xE2, 0xE0,
    0xE8, 0xEA, 0xE0, 0xE2, 0x22, 0x20, 0xEA, 0xEA, 0xE0, 0xEA, 0xE2, 0xE0,
    0x04, 0x04, 0x00, 0xE2, 0x40, 0x40, 0x4A, 0xEA, 0xA0, 0xCA, 0xEA, 0xC0,
    0x68, 0x88, 0x60, 0xCA, 0xAA, 0xC0, 0xE8, 0xE8, 0xE0, 0xE8, 0xE8, 0x80,
    0x68, 0xEA, 0x60, 0xAA, 0xEA, 0xA0, 0xE4, 0x44, 0xE0, 0x22, 0x22, 0xC0,
    0xAA, 0xCA, 0xA0, 0x88, 0x88, 0xE0, 0xAE, 0xEA, 0xA0, 0xAE, 0xEE, 0xA0,
    0x4A, 0xAA, 0x40, 0xCA, 0xC8, 0x80, 0x4A, 0xAE, 0x60, 0xCA, 0xEC, 0xA0,
    0x68, 0x42, 0xC0, 0xE4, 0x44, 0x40, 0xAA, 0xAA, 0x60, 0xAA, 0xA4, 0x40,
    0xAA, 0xEE, 0xA0, 0xAA, 0x4E, 0xA0, 0xAA, 0x44, 0x40, 0xE2, 0x48, 0xE0,
    0x00, 0x00, 0x0E,
};

/* --- Glyph descriptors (index 0 is reserved) --- */
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    { .bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 0, .adv_w = 80, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 0, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 3, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 6, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 9, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 12, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 15, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 18, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 21, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 24, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 27, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 30, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 33, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 36, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 39, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 42, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 45, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 48, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 51, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 54, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 57, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 60, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 63, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 66, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 69, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 72, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 75, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 78, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 81, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 84, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 87, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 90, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 93, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 96, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 99, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 102, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 105, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 108, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 111, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 114, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 117, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 120, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 123, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 126, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 129, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
    { .bitmap_index = 132, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0 },
};

/* --- Unicode list (offsets from range_start) for sparse cmap --- */
static const uint16_t unicode_list_0[] = {
    0x0000, 0x0001, 0x0005, 0x000B, 0x000C, 0x000D, 0x000E, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019, 0x001A, 0x001F, 0x0021, 0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027, 0x0028, 0x0029, 0x002A, 0x002B, 0x002C, 0x002D, 0x002E, 0x002F, 0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003A, 0x003F
};

/* --- Character maps: single sparse range --- */
static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x0020, .range_length = 64, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = 46,
        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

/* --- Font descriptor --- */
static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,  /* LV_FONT_FMT_TXT_PLAIN */
};

/* --- Public font --- */
const lv_font_t lv_font_cube_6px = {
    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 6,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = 0,
    .underline_thickness = 0,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};

