#!/usr/bin/env python3
"""Convert 6px_font.h (matrixserver bitmap format) to an LVGL v9 font .c file.

Run once after changing 6px_font.h:
    python3 tools/gen_font.py > shared/src/lv_font_cube_6px.c

The output is committed to the repo so the build never needs Python.
"""

import re
import sys
from pathlib import Path

FONT_W = 4
FONT_H = 6

# Map the glyph variable names from 6px_font.h to their Unicode codepoints.
NAME_TO_CP = {
    **{f"char_{d}": 0x30 + d for d in range(10)},
    **{f"char_{chr(c)}": c for c in range(ord("A"), ord("Z") + 1)},
    "char_colon": ord(":"),
    "char_dot": ord("."),
    "char_comma": ord(","),
    "char_minus": ord("-"),
    "char_plus": ord("+"),
    "char_underscore": ord("_"),
    "char_exclamation": ord("!"),
    "char_question": ord("?"),
    "char_percent": ord("%"),
    # "char_matrix" is a decorative glyph from the source font; skip it —
    # LVGL can't map it to a standard codepoint.
}


def parse_glyphs(src: str) -> dict[str, list[tuple[int, int]]]:
    """Return {glyph_name: [(x, y), ...]} for every const Bitmap1bpp."""
    pattern = re.compile(
        r"const\s+Bitmap1bpp\s+(\w+)\s*=\s*\{([^}]*)\};",
        re.DOTALL,
    )
    coord_re = re.compile(r"Vector2i\(\s*(\d+)\s*,\s*(\d+)\s*\)")
    out = {}
    for m in pattern.finditer(src):
        name, body = m.group(1), m.group(2)
        pixels = [(int(x), int(y)) for x, y in coord_re.findall(body)]
        out[name] = pixels
    return out


def pack_glyph(pixels: list[tuple[int, int]]) -> bytes:
    """Pack a 4x6 glyph into 3 bytes. Pixel order: row-major, MSB-first."""
    pix_set = set(pixels)
    bits = []
    for y in range(FONT_H):
        for x in range(FONT_W):
            bits.append(1 if (x, y) in pix_set else 0)
    # 24 bits → 3 bytes, MSB first within each byte.
    out = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            if i + j < len(bits) and bits[i + j]:
                byte |= 0x80 >> j
        out.append(byte)
    return bytes(out)


def c_hex_array(data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    src = (root / "tools" / "6px_font.h").read_text()
    raw = parse_glyphs(src)

    # Collect codepoint → glyph_dsc entry, sorted by codepoint.
    # Glyph id 0 is reserved (an empty dsc at index 0).
    glyphs = []  # list of (codepoint, pixels_or_None)
    # Space: present in font source by clearing the bitmap; define an empty glyph
    # with a non-zero advance so text with spaces renders.
    glyphs.append((ord(" "), None))

    for name, cp in NAME_TO_CP.items():
        if name not in raw:
            print(f"WARNING: {name} missing from source", file=sys.stderr)
            continue
        glyphs.append((cp, raw[name]))

    glyphs.sort(key=lambda g: g[0])

    # Build the concatenated glyph bitmap + glyph_dsc entries.
    bitmap = bytearray()
    dsc_entries = [
        # id 0 is reserved: empty placeholder, adv_w=0.
        {"bitmap_index": 0, "adv_w": 0, "box_w": 0, "box_h": 0, "ofs_x": 0, "ofs_y": 0},
    ]
    ADV_W = 5 * 16  # 5-pixel advance (4px glyph + 1px gap), 28.4 fixed format.
    for cp, pixels in glyphs:
        if pixels is None or len(pixels) == 0:
            # Empty glyph (space): no bitmap contribution, box 0x0 so renderer skips.
            dsc_entries.append(
                {
                    "bitmap_index": len(bitmap),
                    "adv_w": ADV_W,
                    "box_w": 0,
                    "box_h": 0,
                    "ofs_x": 0,
                    "ofs_y": 0,
                }
            )
        else:
            dsc_entries.append(
                {
                    "bitmap_index": len(bitmap),
                    "adv_w": ADV_W,
                    "box_w": FONT_W,
                    "box_h": FONT_H,
                    # ofs_y=0 with base_line=0 means the glyph's top sits at the top
                    # of the line — matches our flat 6-row design.
                    "ofs_x": 0,
                    "ofs_y": 0,
                }
            )
            bitmap.extend(pack_glyph(pixels))

    # Build the sparse-tiny cmap.
    range_start = 0x20  # space
    range_end = max(cp for cp, _ in glyphs)  # e.g. '_' == 0x5F
    range_length = range_end - range_start + 1
    unicode_list = [cp - range_start for cp, _ in glyphs]

    # Emit the C source.
    out = []
    out.append("/* Generated by tools/gen_font.py from 6px_font.h. Do not edit. */")
    out.append(
        "/* Source font: matrixserver 4x6 bitmap. Coverage: space, A-Z, 0-9, ! ? % + - . , : _ */"
    )
    out.append("")
    out.append("#ifdef LV_LVGL_H_INCLUDE_SIMPLE")
    out.append('    #include "lvgl.h"')
    out.append("#else")
    out.append('    #include "../../lib/lvgl/lvgl.h"')
    out.append("#endif")
    out.append("")
    out.append("/* --- Glyph bitmap (1bpp, packed, MSB-first) --- */")
    out.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    out.append(c_hex_array(bytes(bitmap)))
    out.append("};")
    out.append("")
    out.append("/* --- Glyph descriptors (index 0 is reserved) --- */")
    out.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    for d in dsc_entries:
        out.append(
            f"    {{ .bitmap_index = {d['bitmap_index']}, "
            f".adv_w = {d['adv_w']}, "
            f".box_w = {d['box_w']}, .box_h = {d['box_h']}, "
            f".ofs_x = {d['ofs_x']}, .ofs_y = {d['ofs_y']} }},"
        )
    out.append("};")
    out.append("")
    out.append("/* --- Unicode list (offsets from range_start) for sparse cmap --- */")
    out.append("static const uint16_t unicode_list_0[] = {")
    out.append("    " + ", ".join(f"0x{u:04X}" for u in unicode_list))
    out.append("};")
    out.append("")
    out.append("/* --- Character maps: single sparse range --- */")
    out.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    out.append("    {")
    out.append(
        f"        .range_start = 0x{range_start:04X}, .range_length = {range_length}, .glyph_id_start = 1,"
    )
    out.append(
        f"        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = {len(unicode_list)},"
    )
    out.append("        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY")
    out.append("    }")
    out.append("};")
    out.append("")
    out.append("/* --- Font descriptor --- */")
    out.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    out.append("    .glyph_bitmap = glyph_bitmap,")
    out.append("    .glyph_dsc = glyph_dsc,")
    out.append("    .cmaps = cmaps,")
    out.append("    .kern_dsc = NULL,")
    out.append("    .kern_scale = 0,")
    out.append("    .cmap_num = 1,")
    out.append("    .bpp = 1,")
    out.append("    .kern_classes = 0,")
    out.append("    .bitmap_format = 0,  /* LV_FONT_FMT_TXT_PLAIN */")
    out.append("};")
    out.append("")
    out.append("/* --- Public font --- */")
    out.append("const lv_font_t lv_font_cube_6px = {")
    out.append("    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,")
    out.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    out.append(f"    .line_height = {FONT_H},")
    out.append("    .base_line = 0,")
    out.append("    .subpx = LV_FONT_SUBPX_NONE,")
    out.append("    .underline_position = 0,")
    out.append("    .underline_thickness = 0,")
    out.append("    .dsc = &font_dsc,")
    out.append("    .fallback = NULL,")
    out.append("    .user_data = NULL,")
    out.append("};")
    out.append("")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
